// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  header: dynamic(() => import("./Header")),
  heading_and_text: dynamic(() => import("./HeadingAndText")),
  image_slider: dynamic(() => import("./ImageSlider")),
  paragraph: dynamic(() => import("./Paragraph")),
  service_item: dynamic(() => import("./ServiceItem")),
};
