import GlobalNavigation from '../components/GlobalNavigation';
import './globals.css';
import { Manrope } from 'next/font/google';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata = {
  title: 'Outstanding Cleaning Services',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <GlobalNavigation />
        {children}
      </body>
    </html>
  );
}
